[build]
  publish = "YesOrNo"

[[headers]]
  for = "/Build/*.br"
  [headers.values]
    Content-Encoding = "br"

[[headers]]
  for = "/Build/*.wasm.br"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "br"

[[headers]]
  for = "/Build/*.js.br"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "br"

[[headers]]
  for = "/Build/*.data.br"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Encoding = "br"